// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<Record<string, any>>;

export function GetSnapshot():Promise<main.Snapshot>;

export function JiraDetail(arg1:string):Promise<main.JiraIssueDetail>;

export function JiraMove(arg1:string,arg2:string):Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function Refresh():Promise<void>;

export function SaveCSV(arg1:string,arg2:string):Promise<string>;

export function SaveConfig(arg1:string,arg2:string):Promise<string>;
