// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {confluence} from '../models';
import {main} from '../models';

export function ConfluenceSpaces():Promise<Array<confluence.Space>>;

export function DeleteNote(arg1:number):Promise<string>;

export function DownloadNoteAudio(arg1:number,arg2:boolean):Promise<main.AudioDownloadResult>;

export function GenerateMinutesFromAudio(arg1:number,arg2:string):Promise<main.NoteAI>;

export function GetAIConfig():Promise<main.AIConfig>;

export function GetAuthorMappings():Promise<main.AuthorMappingData>;

export function GetConfig():Promise<Record<string, any>>;

export function GetEntities():Promise<Array<main.Entity>>;

export function GetMembers():Promise<Array<main.Member>>;

export function GetSnapshot():Promise<main.Snapshot>;

export function GetTeams():Promise<Array<main.Team>>;

export function HasFFmpeg():Promise<boolean>;

export function HasPython():Promise<boolean>;

export function JiraDetail(arg1:string):Promise<main.JiraIssueDetail>;

export function JiraMove(arg1:string,arg2:string):Promise<string>;

export function ListNotes(arg1:string):Promise<Array<main.Note>>;

export function OpenURL(arg1:string):Promise<void>;

export function ReadAudioBase64(arg1:string):Promise<string>;

export function Refresh():Promise<void>;

export function SaveAIConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveAuthorMappings(arg1:Array<main.AliasEntry>):Promise<string>;

export function SaveCSV(arg1:string,arg2:string):Promise<string>;

export function SaveConfig(arg1:string,arg2:string):Promise<string>;

export function SaveEntities(arg1:Array<main.Entity>):Promise<string>;

export function SaveMembers(arg1:Array<main.Member>):Promise<string>;

export function SaveNote(arg1:main.Note):Promise<main.NoteResult>;

export function SaveNoteAudio(arg1:number,arg2:string,arg3:string):Promise<main.NoteResult>;

export function SaveTeams(arg1:Array<main.Team>):Promise<string>;

export function ShareNote(arg1:number,arg2:string):Promise<main.NoteResult>;

export function SummarizeNote(arg1:main.Note):Promise<main.NoteAI>;

export function SummarizeWeek(arg1:string,arg2:number):Promise<string>;

export function WeeklyReport(arg1:string,arg2:number):Promise<main.WeekReport>;

export function WeeklyReportUsers():Promise<Array<string>>;
