// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAuthorMappings():Promise<main.AuthorMappingData>;

export function GetConfig():Promise<Record<string, any>>;

export function GetEntities():Promise<Array<main.Entity>>;

export function GetSnapshot():Promise<main.Snapshot>;

export function JiraDetail(arg1:string):Promise<main.JiraIssueDetail>;

export function JiraMove(arg1:string,arg2:string):Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function Refresh():Promise<void>;

export function SaveAuthorMappings(arg1:Array<main.AliasEntry>):Promise<string>;

export function SaveCSV(arg1:string,arg2:string):Promise<string>;

export function SaveConfig(arg1:string,arg2:string):Promise<string>;

export function SaveEntities(arg1:Array<main.Entity>):Promise<string>;

export function SummarizeWeek(arg1:string,arg2:number):Promise<string>;

export function WeeklyReport(arg1:string,arg2:number):Promise<main.WeekReport>;

export function WeeklyReportUsers():Promise<Array<string>>;
