// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAuthorMappings() {
  return window['go']['main']['App']['GetAuthorMappings']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function JiraDetail(arg1) {
  return window['go']['main']['App']['JiraDetail'](arg1);
}

export function JiraMove(arg1, arg2) {
  return window['go']['main']['App']['JiraMove'](arg1, arg2);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function SaveAuthorMappings(arg1) {
  return window['go']['main']['App']['SaveAuthorMappings'](arg1);
}

export function SaveCSV(arg1, arg2) {
  return window['go']['main']['App']['SaveCSV'](arg1, arg2);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SummarizeWeek(arg1, arg2) {
  return window['go']['main']['App']['SummarizeWeek'](arg1, arg2);
}

export function WeeklyReport(arg1, arg2) {
  return window['go']['main']['App']['WeeklyReport'](arg1, arg2);
}

export function WeeklyReportUsers() {
  return window['go']['main']['App']['WeeklyReportUsers']();
}
