// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfluenceSpaces() {
  return window['go']['main']['App']['ConfluenceSpaces']();
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DownloadNoteAudio(arg1, arg2) {
  return window['go']['main']['App']['DownloadNoteAudio'](arg1, arg2);
}

export function GenerateMinutesFromAudio(arg1, arg2) {
  return window['go']['main']['App']['GenerateMinutesFromAudio'](arg1, arg2);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetAuthorMappings() {
  return window['go']['main']['App']['GetAuthorMappings']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEntities() {
  return window['go']['main']['App']['GetEntities']();
}

export function GetMembers() {
  return window['go']['main']['App']['GetMembers']();
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function GetTeams() {
  return window['go']['main']['App']['GetTeams']();
}

export function HasFFmpeg() {
  return window['go']['main']['App']['HasFFmpeg']();
}

export function HasPython() {
  return window['go']['main']['App']['HasPython']();
}

export function JiraDetail(arg1) {
  return window['go']['main']['App']['JiraDetail'](arg1);
}

export function JiraMove(arg1, arg2) {
  return window['go']['main']['App']['JiraMove'](arg1, arg2);
}

export function KeycloakConfigured() {
  return window['go']['main']['App']['KeycloakConfigured']();
}

export function KeycloakLoginStats(arg1, arg2) {
  return window['go']['main']['App']['KeycloakLoginStats'](arg1, arg2);
}

export function KosmosAIConfigured() {
  return window['go']['main']['App']['KosmosAIConfigured']();
}

export function KosmosUsage(arg1, arg2) {
  return window['go']['main']['App']['KosmosUsage'](arg1, arg2);
}

export function ListNotes(arg1) {
  return window['go']['main']['App']['ListNotes'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ReadAudioBase64(arg1) {
  return window['go']['main']['App']['ReadAudioBase64'](arg1);
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function SaveAIConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAIConfig'](arg1, arg2, arg3, arg4);
}

export function SaveAuthorMappings(arg1) {
  return window['go']['main']['App']['SaveAuthorMappings'](arg1);
}

export function SaveCSV(arg1, arg2) {
  return window['go']['main']['App']['SaveCSV'](arg1, arg2);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SaveEntities(arg1) {
  return window['go']['main']['App']['SaveEntities'](arg1);
}

export function SaveMembers(arg1) {
  return window['go']['main']['App']['SaveMembers'](arg1);
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}

export function SaveNoteAudio(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveNoteAudio'](arg1, arg2, arg3);
}

export function SaveTeams(arg1) {
  return window['go']['main']['App']['SaveTeams'](arg1);
}

export function ShareNote(arg1, arg2) {
  return window['go']['main']['App']['ShareNote'](arg1, arg2);
}

export function SummarizeNote(arg1) {
  return window['go']['main']['App']['SummarizeNote'](arg1);
}

export function SummarizeWeek(arg1, arg2) {
  return window['go']['main']['App']['SummarizeWeek'](arg1, arg2);
}

export function WeeklyReport(arg1, arg2) {
  return window['go']['main']['App']['WeeklyReport'](arg1, arg2);
}

export function WeeklyReportUsers() {
  return window['go']['main']['App']['WeeklyReportUsers']();
}
